app/app/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('website.urls')),
    path('doctor/', include('doctor.urls')),
    path('lab/', include('lab.urls')),
    path('agent/', include('agent.urls')),
    path('patient/', include('patient.urls')),
    path('admin/', include('core.urls')),
    path('admin/location/', include('location.urls')),
    path('admin/healthcare/', include('healthcare.urls')),
    path('admin/warehouse/', include('warehouse.urls')),
    path('admin/services/', include('services.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/core/urls.py
from django.urls import path
from .views import (
    LoginView, Dashboard, Logout,
    DisciplineList, DisciplineCreate, DisciplineUpdate,
    DisciplineDelete, SubDisciplineList, SubDisciplineCreate,
    SubDisciplineUpdate, SubDisciplineDelete, UniversityList,
    UniversityCreate, UniversityUpdate, UniversityDelete,
    DegreeList, DegreeCreate, DegreeUpdate, DegreeDelete,
    DesignationList, DesignationCreate, DesignationUpdate,
    DesignationDelete, get_university_via_degree, BrandList,
    BrandCreate, BrandUpdate, BrandDelete, ManufacturerList,
    ManufacturerCreate, ManufacturerUpdate, ManufacturerDelete,
    GroupList, GroupCreate, GroupUpdate, AgentList, AgentCreate,
    AgentProfileView, AgentChangePassword, AgentWarehouse,
    AgentWarehouseCreate
)


app_name = 'core'

urlpatterns = [
    path('login/', LoginView.as_view(), name='admin_login'),
    path('logout/', Logout.as_view(), name='admin_logout'),
    path('dashboard/', Dashboard.as_view(), name='admin_dashboard'),
    path('disciplines/', DisciplineList.as_view(), name='discipline_list'),
    path('disciplines/create/', DisciplineCreate.as_view(), name='discipline_add'),
    path('disciplines/update/<slug>', DisciplineUpdate.as_view(), name='discipline_update'),
    path('disciplines/delete/<slug>', DisciplineDelete.as_view(), name='discipline_delete'),
    path('sub-disciplines/', SubDisciplineList.as_view(), name='sub_discipline_list'),
    path('sub-disciplines/create/', SubDisciplineCreate.as_view(), name='sub_discipline_add'),
    path('sub-disciplines/update/<slug>', SubDisciplineUpdate.as_view(), name='sub_discipline_update'),
    path('sub-disciplines/delete/<slug>', SubDisciplineDelete.as_view(), name='sub_discipline_delete'),
    path('university/', UniversityList.as_view(), name='university_list'),
    path('university/create/', UniversityCreate.as_view(), name='university_add'),
    path('university/update/<slug>', UniversityUpdate.as_view(), name='university_update'),
    path('university/delete/<slug>', UniversityDelete.as_view(), name='university_delete'),
    path('degree/', DegreeList.as_view(), name='degree_list'),
    path('degree/create/', DegreeCreate.as_view(), name='degree_add'),
    path('degree/update/<slug>', DegreeUpdate.as_view(), name='degree_update'),
    path('degree/delete/<slug>', DegreeDelete.as_view(), name='degree_delete'),
    path('designation/', DesignationList.as_view(), name='designation_list'),
    path('designation/create/', DesignationCreate.as_view(), name='designation_add'),
    path('designation/update/<slug>', DesignationUpdate.as_view(), name='designation_update'),
    path('designation/delete/<slug>', DesignationDelete.as_view(), name='designation_delete'),
    path('degree/retrieve-via-university/', get_university_via_degree, name='retrieve_deg_via_uni'),
    path('brand/', BrandList.as_view(), name='brand_list'),
    path('brand/create/', BrandCreate.as_view(), name='brand_add'),
    path('brand/update/<slug>', BrandUpdate.as_view(), name='brand_update'),
    path('brand/delete/<slug>', BrandDelete.as_view(), name='brand_delete'),
    path('manufacturer/', ManufacturerList.as_view(), name='manufacturer_list'),
    path('manufacturer/create/', ManufacturerCreate.as_view(), name='manufacturer_add'),
    path('manufacturer/update/<slug>', ManufacturerUpdate.as_view(), name='manufacturer_update'),
    path('manufacturer/delete/<slug>', ManufacturerDelete.as_view(), name='manufacturer_delete'),
    path('groups/', GroupList.as_view(), name='group_list'),
    path('groups/create/', GroupCreate.as_view(), name='group_add'),
    path('groups/<pk>/update/', GroupUpdate.as_view(), name='group_update'),
    path('agents/', AgentList.as_view(), name='agent_list'),
    path('agents/create/', AgentCreate.as_view(), name='agent_add'),
    path('agents/update/<pk>/profile', AgentProfileView.as_view(), name='agent_profile_update'),
    path('agents/change-password/<pk>', AgentChangePassword.as_view(), name='agent_password_change'),
    path('agents/<pk>/warehouse', AgentWarehouse.as_view(), name='agent_warehouse'),
    path('agents/<pk>/warehouse/add', AgentWarehouseCreate.as_view(), name='agent_warehouse_add'),
]

app/core/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group
from django.utils.translation import gettext as _
from django.core.validators import MinLengthValidator
from .models import Designation, Location
from warehouse.models import AgentProfile


class AdminLogin(forms.Form):
    phone_number = forms.IntegerField(
        label=_('phone_number'),
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': _('enter_phone_number_login_form')
        })
    )
    password = forms.CharField(
        label=_('password'),
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': _('enter_password_login_form')
        })
    )


class UserGroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = '__all__'


class AgentRegistrationForm(forms.Form):
    first_name = forms.CharField(max_length=255)
    middle_name = forms.CharField(max_length=255, required=False)
    last_name = forms.CharField(max_length=255)
    designation = forms.ModelChoiceField(
        queryset=Designation.objects.all()
    )
    location = forms.ModelChoiceField(
        queryset=Location.objects.all()
    )
    phone_number = forms.CharField(
        max_length=10,
        validators=[MinLengthValidator(10)]
    )
    password = forms.CharField(
        max_length=50,
        widget=forms.PasswordInput
    )
    remark = forms.CharField(
        required=False,
        widget=forms.Textarea
    )

    def clean(self):
        cleaned_data = super().clean()
        phone_number = cleaned_data.get("phone_number")
        if get_user_model().objects.filter(phone_number=phone_number).exists():
            self.add_error('phone_number', 'User with phone number exists.')
        for char in phone_number:
            if not char.isdigit():
                self.add_error('phone_number', 'Please Only Enter Numeric Digits.')


class AgentProfileForm(forms.ModelForm):
    class Meta:
        model = AgentProfile
        fields = [
            'first_name', 'middle_name', 'last_name',
            'location', 'designation', 'permanent_address', 'profile_pic',
            'remark'
        ]


class AgentPasswordChangeForm(forms.Form):
    password = forms.CharField(
        max_length=50,
        widget=forms.PasswordInput
    )
    password_confirmation = forms.CharField(
        max_length=50,
        widget=forms.PasswordInput
    )


class AgentWarehouseForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        qs = kwargs.pop('qs')
        super(AgentWarehouseForm, self).__init__(*args, **kwargs)
        self.fields['warehouse'].queryset = qs

    class Meta:
        model = AgentProfile
        fields = ['warehouse']

app/core/views.py
from django.views.generic import (
    FormView, TemplateView, RedirectView, ListView,
    CreateView, UpdateView, DeleteView, DetailView
)
from django.contrib.auth import get_user_model
from django.db.models import F, Q
from django.http import HttpResponseRedirect, JsonResponse
from django.utils.translation import gettext as _
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse_lazy
from django.contrib.auth.models import Group
from django.db import transaction
from django.contrib.messages.views import SuccessMessageMixin
from website.mixins import CheckAdminUserMixin
from .forms import (
    AdminLogin, UserGroupForm, AgentRegistrationForm, AgentProfileForm,
    AgentPasswordChangeForm, AgentWarehouseForm
)
from .constants import STAFF, AGENT
from .models import (
    Discipline, SubDiscipline, University, Degree,
    Designation, MedicineBrand, MedicineCompany
)
from warehouse.models import AgentProfile, WareHouse


class LoginView(FormView):
    template_name = 'core/admin/login.html'
    http_method_names = ['get', 'post']
    form_class = AdminLogin
    success_url = reverse_lazy('core:admin_dashboard')
    failure_url = reverse_lazy('core:admin_login')

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(self.success_url)
        return self.render_to_response(self.get_context_data())

    def form_valid(self, form):
        user = authenticate(
            self.request,
            phone_number=form.cleaned_data['phone_number'],
            password=form.cleaned_data['password']
        )
        if user is None or user.user_type != STAFF or not user.is_active:
            messages.add_message(
                self.request, messages.ERROR, _('invalid_credentials')
            )
            return HttpResponseRedirect(self.failure_url)
        login(self.request, user)
        return HttpResponseRedirect(self.success_url)


class Logout(RedirectView):
    url = reverse_lazy('core:admin_login')

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(Logout, self).get(request, *args, **kwargs)


class Dashboard(CheckAdminUserMixin, TemplateView):
    template_name = 'core/admin/dashboard.html'
    login_url = reverse_lazy('core:admin_login')


class DisciplineList(CheckAdminUserMixin, ListView):
    model = Discipline
    template_name = 'core/discipline/discipline_list.html'
    context_object_name = 'disciplines'


class DisciplineCreate(CheckAdminUserMixin, SuccessMessageMixin, CreateView):
    model = Discipline
    fields = ('name', 'status', 'remark')
    template_name = 'core/discipline/discipline_form.html'
    success_url = reverse_lazy('core:discipline_list')
    success_message = 'Discipline was created successfully'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'Add New Discipline'
        context['form_action'] = reverse_lazy('core:discipline_add')
        return context


class DisciplineUpdate(CheckAdminUserMixin, SuccessMessageMixin, UpdateView):
    model = Discipline
    fields = ('name', 'status', 'remark')
    template_name = 'core/discipline/discipline_form.html'
    success_url = reverse_lazy('core:discipline_list')
    success_message = 'Discipline was updated successfully'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'Update Discipline - ' + self.get_object().name
        context['form_action'] = reverse_lazy(
            'core:discipline_update',
            kwargs={'slug': self.get_object().slug}
        )
        return context


class DisciplineDelete(CheckAdminUserMixin, SuccessMessageMixin, DeleteView):
    model = Discipline
    http_method_names = ['get']
    success_url = reverse_lazy('core:discipline_list')
    success_message = 'Discipline was removed successfully'

    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        obj.delete()
        messages.add_message(
            self.request, messages.SUCCESS, self.success_message
        )
        return HttpResponseRedirect(self.success_url)


class SubDisciplineList(CheckAdminUserMixin, ListView):
    model = SubDiscipline
    template_name = 'core/discipline/subdiscipline_list.html'
    context_object_name = 'disciplines'


class SubDisciplineCreate(CheckAdminUserMixin, SuccessMessageMixin, CreateView):
    model = SubDiscipline
    fields = ('name', 'discipline', 'status', 'remark')
    template_name = 'core/discipline/subdiscipline_form.html'
    success_url = reverse_lazy('core:sub_discipline_list')
    success_message = 'Sub-Discipline was created successfully'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'Add New Sub-Discipline'
        context['form_action'] = reverse_lazy('core:sub_discipline_add')
        return context


class SubDisciplineUpdate(CheckAdminUserMixin, SuccessMessageMixin, UpdateView):
    model = SubDiscipline
    fields = ('name', 'discipline', 'status', 'remark')
    template_name = 'core/discipline/subdiscipline_form.html'
    success_url = reverse_lazy('core:sub_discipline_list')
    success_message = 'Sub-Discipline was updated successfully'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'Update Sub-Discipline - ' + self.get_object().name
        context['form_action'] = reverse_lazy(
            'core:sub_discipline_update',
            kwargs={'slug': self.get_object().slug}
        )
        return context


class SubDisciplineDelete(CheckAdminUserMixin, SuccessMessageMixin, DeleteView):
    model = SubDiscipline
    http_method_names = ['get']
    success_url = reverse_lazy('core:sub_discipline_list')
    success_message = 'Sub-Discipline was removed successfully'

    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        obj.delete()
        messages.add_message(
            self.request, messages.SUCCESS, self.success_message
        )
        return HttpResponseRedirect(self.success_url)


class UniversityList(CheckAdminUserMixin, ListView):
    model = University
    template_name = 'core/university/university_list.html'
    context_object_name = 'universities'


class UniversityCreate(CheckAdminUserMixin, SuccessMessageMixin, CreateView):
    model = University
    fields = ('name', 'location', 'website_link', 'status', 'remark')
    template_name = 'core/university/university_form.html'
    success_url = reverse_lazy('core:university_list')
    success_message = 'University was created successfully'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'Add New University'
        context['form_action'] = reverse_lazy('core:university_add')
        return context


class UniversityUpdate(CheckAdminUserMixin, SuccessMessageMixin, UpdateView):
    model = University
    fields = ('name', 'location', 'website_link', 'status', 'remark')
    template_name = 'core/university/university_form.html'
    success_url = reverse_lazy('core:university_list')
    success_message = 'University was updated successfully'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'Update University - ' + self.get_object().name
        context['form_action'] = reverse_lazy(
            'core:university_update',
            kwargs={'slug': self.get_object().slug}
        )
        return context


class UniversityDelete(CheckAdminUserMixin, SuccessMessageMixin, DeleteView):
    model = University
    http_method_names = ['get']
    success_url = reverse_lazy('core:university_list')
    success_message = 'University was removed successfully'

    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        obj.delete()
        messages.add_message(
            self.request, messages.SUCCESS, self.success_message
        )
        return HttpResponseRedirect(self.success_url)


class DegreeList(CheckAdminUserMixin, ListView):
    model = Degree
    template_name = 'core/degree/degree_list.html'
    context_object_name = 'degrees'


class DegreeCreate(CheckAdminUserMixin, SuccessMessageMixin, CreateView):
    model = Degree
    fields = ('title', 'university', 'detail', 'status')
    template_name = 'core/degree/degree_form.html'
    success_url = reverse_lazy('core:degree_list')
    success_message = 'Degree was created successfully'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'Add New Degree'
        context['form_action'] = reverse_lazy('core:degree_add')
        return context


class DegreeUpdate(CheckAdminUserMixin, SuccessMessageMixin, UpdateView):
    model = Degree
    fields = ('title', 'university', 'detail', 'status')
    template_name = 'core/degree/degree_form.html'
    success_url = reverse_lazy('core:degree_list')
    success_message = 'Degree was updated successfully'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_title'] = 'Update Degree - ' + self.get_object().title
        context['form_action'] = reverse_lazy(
            'core:degree_update',
            kwargs={'slug': self.get_object().slug}
        )
        return context


class DegreeDelete(CheckAdminUserMixin, SuccessMessageMixin, DeleteView):
    model = Degree
    http_method_names = ['get']
    success_url = reverse_lazy('core:degree_list')
    success_message = 'Degree was removed successfully'

    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        obj.delete()
        messages.add_message(

app/core/templates/core/designation/designation_form.html
{% extends "core/admin/partials/admin_layout.html" %}
{% load core_extras %}
{% block title %} Designations | ZenWellness {% endblock title %}
{% block content %}
<!-- Content Header -->
<section class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        </div>
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{% url 'core:admin_dashboard' %}">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="{% url 'core:designation_list' %}">Designations</a></li>
            <li class="breadcrumb-item active">{{ form_title }}</li>
        </ol>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card card-success">
              <div class="card-header">
                <h3 class="card-title">{{ form_title }}</h3>
              </div>

              <form role="form" action="{{ form_action }}" method="POST">
                {% csrf_token %}
                <div class="card-body">
                  <div class="form-group">
                    <label>Name</label>
                    {{ form.title | add_class:"form-control" }}
                  </div>
                  <div class="form-group">
                    <label>Status</label>
                     {{ form.status | add_class:"form-control"}}
                  </div>
                  <div class="form-group">
                    <label>Remark</label>
                     {{ form.remark | add_class:"form-control"}}
                  </div>
                </div>

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
        </div>
    </div>

    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">


</section>
<!-- /.content -->
{% endblock content %}

app/core/templates/core/designation/designation_list.html
{% extends "core/admin/partials/admin_layout.html" %}
{% block title %} Designation | ZenWellness {% endblock title %}

{% block content %}
<!-- Content Header -->
<section class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        </div>
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{% url 'core:admin_dashboard' %}">Dashboard</a></li>
            <li class="breadcrumb-item active">Designations</li>
        </ol>
        </div>
    </div>
    <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">List Of Designations</h3>

                <div class="card-tools">
                  <div class="input-group input-group-sm" style="width: 200px;">
                    <a href="{% url 'core:designation_add' %}">
                        <button class="btn btn-primary btn-sm">
                        <i class="fas fa-plus"></i> Add New Designation</button>
                    </a>
                  </div>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body table-responsive p-0">
                <table class="table table-hover">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Title</th>
                      <th>Remark</th>
                      <th>Status</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for designation in designations %}
                      <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ designation.title }}</td>
                        <td>{{ designation.remark | truncatechars:60}}</td>
                        <td>
                          {% if designation.status == 'A' %}
                            <span class="badge bg-success">
                              Active
                            </span>
                          {% else %}
                            <span class="badge bg-danger">
                              Inactive
                            </span>
                          {% endif %}
                        
                        </td>
                        <td>
                          <a href="{% url 'core:designation_update' designation.slug %}">
                              <button class="btn btn-warning btn-sm">
                              <i class="fas fa-edit"></i> Edit</button>
                          </a>
                          <a class="delete_btn" href="{% url 'core:designation_delete' designation.slug %}">
                              <button class="btn btn-danger btn-sm">
                              <i class="fas fa-trash"></i> Delete</button>
                          </a>
                        </td>
                      </tr>                      
                    {% endfor %}
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">


</section>
<!-- /.content -->
{% endblock content %}

{% block scripts %}
  <script>
    $('.delete_btn').on('click', function(e){
      e.preventDefault();
      let url = $(this).attr('href');
      Swal.fire({
        title: 'Are you sure?',
        text: "You won't be able to revert this!",
        type: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Yes, delete it!'
      }).then((result) => {
        if (result.value) {
          window.location.href = url;
        }else{
          Swal.fire(
            'Cancelled!',
            'Deletion Process Stopped.',
            'error'
          )          
        }
      });
    })
  </script>
{% endblock scripts %}