app/app/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('website.urls')),
    path('doctor/', include('doctor.urls')),
    path('lab/', include('lab.urls')),
    path('agent/', include('agent.urls')),
    path('patient/', include('patient.urls')),
    path('admin/', include('core.urls')),
    path('admin/location/', include('location.urls')),
    path('admin/healthcare/', include('healthcare.urls')),
    path('admin/warehouse/', include('warehouse.urls')),
    path('admin/services/', include('services.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/core/urls.py
from django.urls import path
from .views import (
    LoginView, Dashboard, Logout,
    DisciplineList, DisciplineCreate, DisciplineUpdate,
    DisciplineDelete, SubDisciplineList, SubDisciplineCreate,
    SubDisciplineUpdate, SubDisciplineDelete, UniversityList,
    UniversityCreate, UniversityUpdate, UniversityDelete,
    DegreeList, DegreeCreate, DegreeUpdate, DegreeDelete,
    DesignationList, DesignationCreate, DesignationUpdate,
    DesignationDelete, get_university_via_degree, BrandList,
    BrandCreate, BrandUpdate, BrandDelete, ManufacturerList,
    ManufacturerCreate, ManufacturerUpdate, ManufacturerDelete,
    GroupList, GroupCreate, GroupUpdate, AgentList, AgentCreate,
    AgentProfileView, AgentChangePassword, AgentWarehouse,
    AgentWarehouseCreate
)


app_name = 'core'

urlpatterns = [
    path('login/', LoginView.as_view(), name='admin_login'),
    path('logout/', Logout.as_view(), name='admin_logout'),
    path('dashboard/', Dashboard.as_view(), name='admin_dashboard'),
    path('disciplines/', DisciplineList.as_view(), name='discipline_list'),
    path('disciplines/create/', DisciplineCreate.as_view(), name='discipline_add'),
    path('disciplines/update/<slug>', DisciplineUpdate.as_view(), name='discipline_update'),
    path('disciplines/delete/<slug>', DisciplineDelete.as_view(), name='discipline_delete'),
    path('sub-disciplines/', SubDisciplineList.as_view(), name='sub_discipline_list'),
    path('sub-disciplines/create/', SubDisciplineCreate.as_view(), name='sub_discipline_add'),
    path('sub-disciplines/update/<slug>', SubDisciplineUpdate.as_view(), name='sub_discipline_update'),
    path('sub-disciplines/delete/<slug>', SubDisciplineDelete.as_view(), name='sub_discipline_delete'),
    path('university/', UniversityList.as_view(), name='university_list'),
    path('university/create/', UniversityCreate.as_view(), name='university_add'),
    path('university/update/<slug>', UniversityUpdate.as_view(), name='university_update'),
    path('university/delete/<slug>', UniversityDelete.as_view(), name='university_delete'),
    path('degree/', DegreeList.as_view(), name='degree_list'),
    path('degree/create/', DegreeCreate.as_view(), name='degree_add'),
    path('degree/update/<slug>', DegreeUpdate.as_view(), name='degree_update'),
    path('degree/delete/<slug>', DegreeDelete.as_view(), name='degree_delete'),
    path('designation/', DesignationList.as_view(), name='designation_list'),
    path('designation/create/', DesignationCreate.as_view(), name='designation_add'),
    path('designation/update/<slug>', DesignationUpdate.as_view(), name='designation_update'),
    path('designation/delete/<slug>', DesignationDelete.as_view(), name='designation_delete'),
    path('degree/retrieve-via-university/', get_university_via_degree, name='retrieve_deg_via_uni'),
    path('brand/', BrandList.as_view(), name='brand_list'),
    path('brand/create/', BrandCreate.as_view(), name='brand_add'),
    path('brand/update/<slug>', BrandUpdate.as_view(), name='brand_update'),
    path('brand/delete/<slug>', BrandDelete.as_view(), name='brand_delete'),
    path('manufacturer/', ManufacturerList.as_view(), name='manufacturer_list'),
    path('manufacturer/create/', ManufacturerCreate.as_view(), name='manufacturer_add'),
    path('manufacturer/update/<slug>', ManufacturerUpdate.as_view(), name='manufacturer_update'),
    path('manufacturer/delete/<slug>', ManufacturerDelete.as_view(), name='manufacturer_delete'),
    path('groups/', GroupList.as_view(), name='group_list'),
    path('groups/create/', GroupCreate.as_view(), name='group_add'),
    path('groups/<pk>/update/', GroupUpdate.as_view(), name='group_update'),
    path('agents/', AgentList.as_view(), name='agent_list'),
    path('agents/create/', AgentCreate.as_view(), name='agent_add'),
    path('agents/update/<pk>/profile', AgentProfileView.as_view(), name='agent_profile_update'),
    path('agents/change-password/<pk>', AgentChangePassword.as_view(), name='agent_password_change'),
    path('agents/<pk>/warehouse', AgentWarehouse.as_view(), name='agent_warehouse'),
    path('agents/<pk>/warehouse/add', AgentWarehouseCreate.as_view(), name='agent_warehouse_add'),
]

app/healthcare/urls.py
from django.urls import path
from .views import (
    DoctorList, DoctorCreate, DoctorProfileView,
    DoctorDegreeList, DoctorDegreeCreate, DoctorDegreeDeleteView,
    DoctorChangePassword, QuestionChoiceList, QuestionChoiceCreate,
    QuestionChoiceUpdate, QuestionChoiceDelete, QuestionList,
    QuestionCreate, QuestionUpdate, QuestionDelete,
    CounsellingQuestionSetList, CounsellingQuestionSetCreate,
    CounsellingQuestionSetUpdate, CounsellingQuestionSetDelete,
    PatientList, PatientCreate, PatientProfileView,
    PatientConsellingQuestionSets, PatientConsellingQuestionSetCreate,
    PatientConsellingQuestionForm, OrganizationList, OrganizationCreate,
    OrganizationUpdate, OrganizationDelete, DoctorVisitingSchedulesList,
    DoctorVisitingSchedulesCreate, DoctorVisitingSchedulesUpdate,
    DoctorVisitingSchedulesDelete, LabTestItemsList, LabTestItemsCreate,
    LabTestItemsUpdate, LabTestItemsDelete, LabTestsList, LabTestsCreate,
    LabTestsUpdate, LabTestsDelete, LabTestsItems, LabsList, LabsCreate,
    LabsUpdate, LabsDelete, LabsTests, LabAgentList, LabAgentsCreate,
    LabAgentsProfileUpdate
)

app_name = 'healthcare'

urlpatterns = [
    path('doctor/', DoctorList.as_view(), name="doctor_list"),
    path('doctor/create/', DoctorCreate.as_view(), name="doctor_add"),
    path('doctor/profile/<pk>', DoctorProfileView.as_view(), name="doctor_profile_update"),
    path('patient/', PatientList.as_view(), name="patient_list"),
    path('patient/create/', PatientCreate.as_view(), name="patient_add"),
    path('patient/profile/<pk>', PatientProfileView.as_view(), name="patient_profile_update"),
    path('doctor/degree/<pk>', DoctorDegreeList.as_view(), name="doctor_degree_list"),
    path('doctor/degree/<pk>/add', DoctorDegreeCreate.as_view(), name="doctor_degree_add"),
    path('doctor/degree/<pk>/delete', DoctorDegreeDeleteView.as_view(), name="doctor_degree_delete"),
    path('doctor/change-password/<pk>', DoctorChangePassword.as_view(), name="doctor_change_password"),
    path('questions-choices/', QuestionChoiceList.as_view(), name="question_choice"),
    path('questions-choices/create/', QuestionChoiceCreate.as_view(), name="question_choice_add"),
    path('questions-choices/update/<slug>', QuestionChoiceUpdate.as_view(), name="question_choice_update"),
    path('questions-choices/delete/<slug>', QuestionChoiceDelete.as_view(), name="question_choice_delete"),   
    path('questions/', QuestionList.as_view(), name='question_list'),
    path('questions/create/', QuestionCreate.as_view(), name="question_add"),
    path('questions/update/<pk>', QuestionUpdate.as_view(), name="question_update"),
    path('questions/delete/<pk>', QuestionDelete.as_view(), name="question_delete"),   
    path('counselling-question-set/', CounsellingQuestionSetList.as_view(), name='coun_question_set_list'),
    path('counselling-question-set/create/', CounsellingQuestionSetCreate.as_view(), name="coun_question_set_add"),
    path('counselling-question-set/update/<pk>', CounsellingQuestionSetUpdate.as_view(), name="coun_question_set_update"),
    path('counselling-question-set/delete/<pk>', CounsellingQuestionSetDelete.as_view(), name="coun_question_set_delete"),   
    path('counselling/patient/<pk>', PatientConsellingQuestionSets.as_view(), name="patient_counselling_question_sets_list"),   
    path('counselling/patient/create/<pk>', PatientConsellingQuestionSetCreate.as_view(), name="patient_counselling_question_sets_add"),   
    path('counselling/patient/create/form/<pk>', PatientConsellingQuestionForm.as_view(), name="patient_counselling_question_form"),   
    path('organizations/', OrganizationList.as_view(), name='organization_list'),
    path('organizations/create/', OrganizationCreate.as_view(), name='organization_add'),
    path('organizations/update/<slug>', OrganizationUpdate.as_view(), name='organization_update'),
    path('organizations/delete/<slug>', OrganizationDelete.as_view(), name='organization_delete'),
    path('doctor/visiting-hours/<pk>', DoctorVisitingSchedulesList.as_view(), name='doctor_schedule_list'),
    path('doctor/visiting-hours/<pk>/add', DoctorVisitingSchedulesCreate.as_view(), name='doctor_schedule_add'),  
    path('doctor/visiting-hours/<pk>/update', DoctorVisitingSchedulesUpdate.as_view(), name='doctor_schedule_update'),  
    path('doctor/visiting-hours/<pk>/delete', DoctorVisitingSchedulesDelete.as_view(), name='doctor_schedule_delete'),  
    path('lab-test-items/', LabTestItemsList.as_view(), name='lab_test_items_list'),
    path('lab-test-items/create/', LabTestItemsCreate.as_view(), name='lab_test_items_add'),
    path('lab-test-items/update/<pk>', LabTestItemsUpdate.as_view(), name='lab_test_items_update'),
    path('lab-test-items/delete/<pk>', LabTestItemsDelete.as_view(), name='lab_test_items_delete'),
    path('lab-tests/', LabTestsList.as_view(), name='lab_tests_list'),
    path('lab-tests/create/', LabTestsCreate.as_view(), name='lab_tests_add'),
    path('lab-tests/update/<slug>', LabTestsUpdate.as_view(), name='lab_tests_update'),
    path('lab-tests/delete/<slug>', LabTestsDelete.as_view(), name='lab_tests_delete'),
    path('lab-tests/items/<slug>', LabTestsItems.as_view(), name='lab_tests_items'),
    path('labs/', LabsList.as_view(), name='labs_list'),
    path('labs/create/', LabsCreate.as_view(), name='labs_add'),
    path('labs/update/<slug>', LabsUpdate.as_view(), name='labs_update'),
    path('labs/delete/<slug>', LabsDelete.as_view(), name='labs_delete'),
    path('labs/items/<slug>', LabsTests.as_view(), name='labs_tests'),
    path('labs/agents/<slug>', LabAgentList.as_view(), name="lab_agents"),
    path('labs/agents/<slug>/create', LabAgentsCreate.as_view(), name="lab_agents_add"),
    path('labs/agents/<pk>/update', LabAgentsProfileUpdate.as_view(), name="lab_agents_update"),
]

app/lab/urls.py
from django.urls import path
from .views import Dashboard, TestList

app_name = 'lab'

urlpatterns = [
    path('', Dashboard.as_view(), name="dashboard"),
    path('tests/', TestList.as_view(), name="tests_list"),
]

app/lab/models.py
from django.db import models

# Create your models here.

app/lab/views.py
from django.views.generic import (
    TemplateView
)
from healthcare.models import (
    LabAgentProfile
)
from website.mixins import CheckLabAgentUserMixin


class Dashboard(CheckLabAgentUserMixin, TemplateView):
    template_name = 'lab/dashboard.html'


class TestList(CheckLabAgentUserMixin, TemplateView):
    template_name = 'lab/test_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        lab_agent = LabAgentProfile.objects.get(user=self.request.user)
        context['tests'] = lab_agent.lab.tests.all()
        return context

app/healthcare/templates/healthcare/lab/items_form.html
{% extends "core/admin/partials/admin_layout.html" %}
{% load core_extras %}
{% block title %} Lab Test Items | ZenWellness {% endblock title %}
{% block content %}
<!-- Content Header -->
<section class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        </div>
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{% url 'core:admin_dashboard' %}">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="{% url 'healthcare:lab_test_items_list' %}">Lab Test Items</a></li>
            <li class="breadcrumb-item active">{{ form_title }}</li>
        </ol>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card card-success">
              <div class="card-header">
                <h3 class="card-title">{{ form_title }}</h3>
              </div>

              <form role="form" action="{{ form_action }}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="card-body">
                  <div class="form-group">
                    <label>Name</label>
                    {{ form.name | add_class:"form-control" }}
                  </div>
                  <div class="form-group">
                    <label>Remark</label>
                     {{ form.remark | add_class:"form-control"}}
                  </div>
                </div>

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
        </div>
    </div>

    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">


</section>
<!-- /.content -->
{% endblock content %}

app/healthcare/templates/healthcare/lab/items_list.html
{% extends "core/admin/partials/admin_layout.html" %}
{% block title %} Lab Test Items  | ZenWellness {% endblock title %}

{% block content %}
<!-- Content Header -->
<section class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        </div>
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{% url 'core:admin_dashboard' %}">Dashboard</a></li>
            <li class="breadcrumb-item active">Lab Test Items </li>
        </ol>
        </div>
    </div>
    <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">List of Lab Test Items</h3>

                <div class="card-tools">
                  <div class="input-group input-group-sm" style="width: 200px;">
                    <a href="{% url 'healthcare:lab_test_items_add' %}">
                        <button class="btn btn-primary btn-sm">
                        <i class="fas fa-plus"></i> Add New Lab Test Items </button>
                    </a>
                  </div>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body table-responsive p-0">
                <table class="table table-hover">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Name</th>
                      <th>Remark</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for item in items %}
                      <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ item.name }}</td>
                        <td>
                            {{ item.remark }}
                        </td>
                        <td>
                          <a href="{% url 'healthcare:lab_test_items_update' item.pk %}">
                              <button class="btn btn-warning btn-sm">
                              <i class="fas fa-edit"></i> Edit</button>
                          </a>
                          <a class="delete_btn" href="{% url 'healthcare:lab_test_items_delete' item.pk %}">
                              <button class="btn btn-danger btn-sm">
                              <i class="fas fa-trash"></i> Delete</button>
                          </a>
                        </td>
                      </tr>                      
                    {% endfor %}
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">


</section>
<!-- /.content -->
{% endblock content %}

{% block scripts %}
  <script>
    $('.delete_btn').on('click', function(e){
      e.preventDefault();
      let url = $(this).attr('href');
      Swal.fire({
        title: 'Are you sure?',
        text: "You won't be able to revert this!",
        type: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Yes, delete it!'
      }).then((result) => {
        if (result.value) {
          window.location.href = url;
        }else{
          Swal.fire(
            'Cancelled!',
            'Deletion Process Stopped.',
            'error'
          )          
        }
      });
    })
  </script>
{% endblock scripts %}

app/healthcare/templates/healthcare/lab/labs_form.html
{% extends "core/admin/partials/admin_layout.html" %}
{% load core_extras %}
{% block title %} Lab Tests | ZenWellness {% endblock title %}
{% block content %}
<!-- Content Header -->
<section class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        </div>
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{% url 'core:admin_dashboard' %}">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="{% url 'healthcare:lab_tests_list' %}">Lab Tests</a></li>
            <li class="breadcrumb-item active">{{ form_title }}</li>
        </ol>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card card-success">
              <div class="card-header">
                <h3 class="card-title">{{ form_title }}</h3>
              </div>

              <form role="form" action="{{ form_action }}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="card-body">
                  <div class="form-group">
                    <label>Name</label>
                    {{ form.name | add_class:"form-control" }}
                  </div>
                  <div class="form-group">
                    <label>Location</label>
                    {{ form.location | add_class:"form-control select2" }}
                  </div>
                  <div class="form-group">
                    <label>Tests</label>
                    {{ form.tests | add_class:"form-control select2" }}
                  </div>
                  <div class="form-group">
                    <label>Remark</label>
                     {{ form.remark | add_class:"form-control"}}
                  </div>
                </div>

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
        </div>
    </div>

    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">


</section>
<!-- /.content -->
{% endblock content %}

app/healthcare/templates/healthcare/lab/labs_list.html
{% extends "core/admin/partials/admin_layout.html" %}
{% block title %} Labs | ZenWellness {% endblock title %}

{% block content %}
<!-- Content Header -->
<section class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        </div>
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{% url 'core:admin_dashboard' %}">Dashboard</a></li>
            <li class="breadcrumb-item active">Labs </li>
        </ol>
        </div>
    </div>
    <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">List of Labs</h3>

                <div class="card-tools">
                  <div class="input-group input-group-sm" style="width: 200px;">
                    <a href="{% url 'healthcare:labs_add' %}">
                        <button class="btn btn-primary btn-sm">
                        <i class="fas fa-plus"></i> Add New Lab </button>
                    </a>
                  </div>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body table-responsive p-0">
                <table class="table table-hover">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Name</th>
                      <th>Location</th>
                      <th>Remark</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for item in labs %}
                      <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ item.name }}</td>
                        <td>
                            {{ item.location }}
                        </td>
                        <td>
                            {{ item.remark }}
                        </td>
                        <td>
                        <a href="{% url 'healthcare:labs_tests' item.slug %}">
                              <button class="btn btn-success btn-sm">
                              <i class="fas fa-eye"></i> View Tests</button>
                          </a>
                        <a href="{% url 'healthcare:lab_agents' item.slug %}">
                              <button class="btn btn-primary btn-sm">
                              <i class="fas fa-users"></i> Users</button>
                          </a>
                          <a href="{% url 'healthcare:labs_update' item.slug %}">
                              <button class="btn btn-warning btn-sm">
                              <i class="fas fa-edit"></i> Edit</button>
                          </a>
                          <a class="delete_btn" href="{% url 'healthcare:labs_delete' item.slug %}">
                              <button class="btn btn-danger btn-sm">
                              <i class="fas fa-trash"></i> Delete</button>
                          </a>
                        </td>
                      </tr>                      
                    {% endfor %}
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">


</section>
<!-- /.content -->
{% endblock content %}

{% block scripts %}
  <script>
    $('.delete_btn').on('click', function(e){
      e.preventDefault();
      let url = $(this).attr('href');
      Swal.fire({
        title: 'Are you sure?',
        text: "You won't be able to revert this!",
        type: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Yes, delete it!'
      }).then((result) => {
        if (result.value) {
          window.location.href = url;
        }else{
          Swal.fire(
            'Cancelled!',
            'Deletion Process Stopped.',
            'error'
          )          
        }
      });
    })
  </script>
{% endblock scripts %}

app/healthcare/templates/healthcare/lab/tests_form.html
{% extends "core/admin/partials/admin_layout.html" %}
{% load core_extras %}
{% block title %} Lab Tests | ZenWellness {% endblock title %}
{% block content %}
<!-- Content Header -->
<section class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        </div>
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{% url 'core:admin_dashboard' %}">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="{% url 'healthcare:lab_tests_list' %}">Lab Tests</a></li>
            <li class="breadcrumb-item active">{{ form_title }}</li>
        </ol>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card card-success">
              <div class="card-header">
                <h3 class="card-title">{{ form_title }}</h3>
              </div>

              <form role="form" action="{{ form_action }}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="card-body">
                  <div class="form-group">
                    <label>Name</label>
                    {{ form.name | add_class:"form-control" }}
                  </div>
                  <div class="form-group">
                    <label>Home Service ?</label>
                    <br/>
                    {{ form.home_service }}
                  </div>
                  <div class="form-group">
                    <label>Items</label>
                    {{ form.items | add_class:"form-control select2" }}
                  </div>
                  <div class="form-group">
                    <label>Remark</label>
                     {{ form.remark | add_class:"form-control"}}
                  </div>
                </div>

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
        </div>
    </div>

    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">


</section>
<!-- /.content -->
{% endblock content %}

app/healthcare/templates/healthcare/lab/tests_list.html
{% extends "core/admin/partials/admin_layout.html" %}
{% block title %} Lab Tests  | ZenWellness {% endblock title %}

{% block content %}
<!-- Content Header -->
<section class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        </div>
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{% url 'core:admin_dashboard' %}">Dashboard</a></li>
            <li class="breadcrumb-item active">Lab Tests </li>
        </ol>
        </div>
    </div>
    <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">List of Lab Tests</h3>

                <div class="card-tools">
                  <div class="input-group input-group-sm" style="width: 200px;">
                    <a href="{% url 'healthcare:lab_tests_add' %}">
                        <button class="btn btn-primary btn-sm">
                        <i class="fas fa-plus"></i> Add New Lab Test Items </button>
                    </a>
                  </div>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body table-responsive p-0">
                <table class="table table-hover">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Name</th>
                      <th>Home Service</th>
                      <th>Remark</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for item in tests %}
                      <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ item.name }}</td>
                        <td>
                            {% if item.home_service %}
                              Available
                            {% else %}
                              Not Available
                            {% endif %}
                        </td>
                        <td>
                            {{ item.remark }}
                        </td>
                        <td>
                        <a href="{% url 'healthcare:lab_tests_items' item.slug %}">
                              <button class="btn btn-success btn-sm">
                              <i class="fas fa-eye"></i> View Items</button>
                          </a>
                          <a href="{% url 'healthcare:lab_tests_update' item.slug %}">
                              <button class="btn btn-warning btn-sm">
                              <i class="fas fa-edit"></i> Edit</button>
                          </a>
                          <a class="delete_btn" href="{% url 'healthcare:lab_tests_delete' item.slug %}">
                              <button class="btn btn-danger btn-sm">
                              <i class="fas fa-trash"></i> Delete</button>
                          </a>
                        </td>
                      </tr>                      
                    {% endfor %}
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">


</section>
<!-- /.content -->
{% endblock content %}

{% block scripts %}
  <script>
    $('.delete_btn').on('click', function(e){
      e.preventDefault();
      let url = $(this).attr('href');
      Swal.fire({
        title: 'Are you sure?',
        text: "You won't be able to revert this!",
        type: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Yes, delete it!'
      }).then((result) => {
        if (result.value) {
          window.location.href = url;
        }else{
          Swal.fire(
            'Cancelled!',
            'Deletion Process Stopped.',
            'error'
          )          
        }
      });
    })
  </script>
{% endblock scripts %}