app/app/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('website.urls')),
    path('doctor/', include('doctor.urls')),
    path('lab/', include('lab.urls')),
    path('agent/', include('agent.urls')),
    path('patient/', include('patient.urls')),
    path('admin/', include('core.urls')),
    path('admin/location/', include('location.urls')),
    path('admin/healthcare/', include('healthcare.urls')),
    path('admin/warehouse/', include('warehouse.urls')),
    path('admin/services/', include('services.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/doctor/urls.py
from django.urls import path
from .views import Dashboard

app_name = 'doctor'

urlpatterns = [
    path('', Dashboard.as_view(), name='dashboard')
]

app/healthcare/urls.py
from django.urls import path
from .views import (
    DoctorList, DoctorCreate, DoctorProfileView,
    DoctorDegreeList, DoctorDegreeCreate, DoctorDegreeDeleteView,
    DoctorChangePassword, QuestionChoiceList, QuestionChoiceCreate,
    QuestionChoiceUpdate, QuestionChoiceDelete, QuestionList,
    QuestionCreate, QuestionUpdate, QuestionDelete,
    CounsellingQuestionSetList, CounsellingQuestionSetCreate,
    CounsellingQuestionSetUpdate, CounsellingQuestionSetDelete,
    PatientList, PatientCreate, PatientProfileView,
    PatientConsellingQuestionSets, PatientConsellingQuestionSetCreate,
    PatientConsellingQuestionForm, OrganizationList, OrganizationCreate,
    OrganizationUpdate, OrganizationDelete, DoctorVisitingSchedulesList,
    DoctorVisitingSchedulesCreate, DoctorVisitingSchedulesUpdate,
    DoctorVisitingSchedulesDelete, LabTestItemsList, LabTestItemsCreate,
    LabTestItemsUpdate, LabTestItemsDelete, LabTestsList, LabTestsCreate,
    LabTestsUpdate, LabTestsDelete, LabTestsItems, LabsList, LabsCreate,
    LabsUpdate, LabsDelete, LabsTests, LabAgentList, LabAgentsCreate,
    LabAgentsProfileUpdate
)

app_name = 'healthcare'

urlpatterns = [
    path('doctor/', DoctorList.as_view(), name="doctor_list"),
    path('doctor/create/', DoctorCreate.as_view(), name="doctor_add"),
    path('doctor/profile/<pk>', DoctorProfileView.as_view(), name="doctor_profile_update"),
    path('patient/', PatientList.as_view(), name="patient_list"),
    path('patient/create/', PatientCreate.as_view(), name="patient_add"),
    path('patient/profile/<pk>', PatientProfileView.as_view(), name="patient_profile_update"),
    path('doctor/degree/<pk>', DoctorDegreeList.as_view(), name="doctor_degree_list"),
    path('doctor/degree/<pk>/add', DoctorDegreeCreate.as_view(), name="doctor_degree_add"),
    path('doctor/degree/<pk>/delete', DoctorDegreeDeleteView.as_view(), name="doctor_degree_delete"),
    path('doctor/change-password/<pk>', DoctorChangePassword.as_view(), name="doctor_change_password"),
    path('questions-choices/', QuestionChoiceList.as_view(), name="question_choice"),
    path('questions-choices/create/', QuestionChoiceCreate.as_view(), name="question_choice_add"),
    path('questions-choices/update/<slug>', QuestionChoiceUpdate.as_view(), name="question_choice_update"),
    path('questions-choices/delete/<slug>', QuestionChoiceDelete.as_view(), name="question_choice_delete"),   
    path('questions/', QuestionList.as_view(), name='question_list'),
    path('questions/create/', QuestionCreate.as_view(), name="question_add"),
    path('questions/update/<pk>', QuestionUpdate.as_view(), name="question_update"),
    path('questions/delete/<pk>', QuestionDelete.as_view(), name="question_delete"),   
    path('counselling-question-set/', CounsellingQuestionSetList.as_view(), name='coun_question_set_list'),
    path('counselling-question-set/create/', CounsellingQuestionSetCreate.as_view(), name="coun_question_set_add"),
    path('counselling-question-set/update/<pk>', CounsellingQuestionSetUpdate.as_view(), name="coun_question_set_update"),
    path('counselling-question-set/delete/<pk>', CounsellingQuestionSetDelete.as_view(), name="coun_question_set_delete"),   
    path('counselling/patient/<pk>', PatientConsellingQuestionSets.as_view(), name="patient_counselling_question_sets_list"),   
    path('counselling/patient/create/<pk>', PatientConsellingQuestionSetCreate.as_view(), name="patient_counselling_question_sets_add"),   
    path('counselling/patient/create/form/<pk>', PatientConsellingQuestionForm.as_view(), name="patient_counselling_question_form"),   
    path('organizations/', OrganizationList.as_view(), name='organization_list'),
    path('organizations/create/', OrganizationCreate.as_view(), name='organization_add'),
    path('organizations/update/<slug>', OrganizationUpdate.as_view(), name='organization_update'),
    path('organizations/delete/<slug>', OrganizationDelete.as_view(), name='organization_delete'),
    path('doctor/visiting-hours/<pk>', DoctorVisitingSchedulesList.as_view(), name='doctor_schedule_list'),
    path('doctor/visiting-hours/<pk>/add', DoctorVisitingSchedulesCreate.as_view(), name='doctor_schedule_add'),  
    path('doctor/visiting-hours/<pk>/update', DoctorVisitingSchedulesUpdate.as_view(), name='doctor_schedule_update'),  
    path('doctor/visiting-hours/<pk>/delete', DoctorVisitingSchedulesDelete.as_view(), name='doctor_schedule_delete'),  
    path('lab-test-items/', LabTestItemsList.as_view(), name='lab_test_items_list'),
    path('lab-test-items/create/', LabTestItemsCreate.as_view(), name='lab_test_items_add'),
    path('lab-test-items/update/<pk>', LabTestItemsUpdate.as_view(), name='lab_test_items_update'),
    path('lab-test-items/delete/<pk>', LabTestItemsDelete.as_view(), name='lab_test_items_delete'),
    path('lab-tests/', LabTestsList.as_view(), name='lab_tests_list'),
    path('lab-tests/create/', LabTestsCreate.as_view(), name='lab_tests_add'),
    path('lab-tests/update/<slug>', LabTestsUpdate.as_view(), name='lab_tests_update'),
    path('lab-tests/delete/<slug>', LabTestsDelete.as_view(), name='lab_tests_delete'),
    path('lab-tests/items/<slug>', LabTestsItems.as_view(), name='lab_tests_items'),
    path('labs/', LabsList.as_view(), name='labs_list'),
    path('labs/create/', LabsCreate.as_view(), name='labs_add'),
    path('labs/update/<slug>', LabsUpdate.as_view(), name='labs_update'),
    path('labs/delete/<slug>', LabsDelete.as_view(), name='labs_delete'),
    path('labs/items/<slug>', LabsTests.as_view(), name='labs_tests'),
    path('labs/agents/<slug>', LabAgentList.as_view(), name="lab_agents"),
    path('labs/agents/<slug>/create', LabAgentsCreate.as_view(), name="lab_agents_add"),
    path('labs/agents/<pk>/update', LabAgentsProfileUpdate.as_view(), name="lab_agents_update"),
]

app/doctor/models.py
from django.db import models

# Create your models here.

app/healthcare/models.py
import time
from django.db import models
from django.contrib.auth import get_user_model
from core.models import (
    University, Degree, Designation, SubDiscipline
)
from location.models import Location
from core.utils import get_unique_slug


def user_directory_path(instance, filename):
    name = str(int(time.time()))+'.'+filename.split('.')[-1]
    return 'user_{0}/{1}'.format(instance.user.id, name)


def organization_directory_path(instance, filename):
    name = str(int(time.time()))+'.'+filename.split('.')[-1]
    return 'org_{0}/{1}'.format(instance.id, name)


QUESTION_TYPES = (
    ('D', 'Description'),
    ('O', 'Option'),
)
ACTIVE = 'A'
INACTIVE = 'I'
APPROVED = 'A'
UNAPPROVED = 'U'
STATUS = (
    (ACTIVE, 'Active'),
    (INACTIVE, 'Inactive'),
)
GENDER = (
    ('M', 'Male'),
    ('F', 'Female'),
)
APPROVAL_STATUS = (
    (APPROVED, 'Approved'),
    (UNAPPROVED, 'Unapproved'),
)


class DoctorProfile(models.Model):
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )
    designation = models.ForeignKey(
        Designation,
        on_delete=models.PROTECT
    )
    discipline = models.ForeignKey(
        SubDiscipline,
        on_delete=models.PROTECT
    )
    first_name = models.CharField(
        max_length=255
    )
    middle_name = models.CharField(
        max_length=255,
        blank=True,
        null=True
    )
    last_name = models.CharField(
        max_length=255
    )
    permanent_address = models.ForeignKey(
        Location,
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    profile_pic = models.ImageField(
        upload_to=user_directory_path,
        blank=True,
        null=True
    )
    approval_status = models.CharField(
        max_length=2,
        choices=APPROVAL_STATUS,
        default=UNAPPROVED,
        null=True
    )

    remark = models.TextField(blank=True, null=True)

    def __str__(self):
        name = self.first_name + ' '
        if self.middle_name:
            name += self.middle_name + ' '
        return name + ' ' + self.last_name + ' - ' + self.user.phone_number


class DoctorDegree(models.Model):
    doctor = models.ForeignKey(DoctorProfile, on_delete=models.CASCADE)
    degree = models.ForeignKey(Degree, on_delete=models.CASCADE)
    university = models.ForeignKey(University, on_delete=models.CASCADE)

    def __str__(self):
        return self.doctor

    class Meta:
        unique_together = ('doctor', 'degree', 'university')


class Organization(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(
        unique=True,
        allow_unicode=True
    )
    image = models.ImageField(
        upload_to=organization_directory_path,
        blank=True,
        null=True
    )
    remark = models.TextField(blank=True, null=True)
    location = models.ForeignKey(
        Location,
        on_delete=models.PROTECT
    )

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = get_unique_slug(self, 'name', 'slug')
        super().save(*args, **kwargs)


class DoctorVistingSchedules(models.Model):
    doctor = models.ForeignKey(
        DoctorProfile,
        on_delete=models.PROTECT
    )
    date = models.DateField()
    in_time = models.TimeField()
    out_time = models.TimeField()
    organization = models.ForeignKey(
        Organization,
        on_delete=models.PROTECT
    )
    remark = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('doctor', 'date', 'organization', 'in_time', 'out_time')


class PatientProfile(models.Model):
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )
    designation = models.ForeignKey(
        Designation,
        on_delete=models.PROTECT
    )
    first_name = models.CharField(
        max_length=255
    )
    middle_name = models.CharField(
        max_length=255,
        blank=True,
        null=True
    )
    last_name = models.CharField(
        max_length=255
    )
    gender = models.CharField(
        max_length=1,
        choices=GENDER
    )
    date_of_birth = models.DateField(
        null=True
    )
    permanent_address = models.ForeignKey(
        Location,
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    profile_pic = models.ImageField(
        upload_to=user_directory_path,
        blank=True,
        null=True
    )
    approval_status = models.CharField(
        max_length=2,
        choices=APPROVAL_STATUS,
        default=UNAPPROVED,
    )
    remark = models.TextField(blank=True, null=True)
    registered_by = models.ForeignKey(
        get_user_model(),
        on_delete=models.PROTECT,
        null=True,
        related_name='registered_by'
    )

    def __str__(self):
        name = self.first_name + ' '
        if self.middle_name:
            name += self.middle_name + ' '
        return name + ' ' + self.last_name + ' - ' + self.user.phone_number


class QuestionChoices(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Question(models.Model):
    question = models.CharField(
        max_length=255,
        unique=True
    )
    question_type = models.CharField(
        max_length=1,
        choices=QUESTION_TYPES
    )
    question_choices = models.ManyToManyField(
        QuestionChoices,
        blank=True,
    )

    def __str__(self):
        return self.question


class ConsellingQuestionSets(models.Model):
    name = models.CharField(max_length=255)
    question = models.ManyToManyField(
        Question
    )

    def __str__(self):
        return self.name


class ConsellingQuestionSetsAnswers(models.Model):
    question = models.ForeignKey(
        Question,
        on_delete=models.CASCADE
    )
    answer_description = models.TextField(null=True)
    answer_choice = models.ForeignKey(
        QuestionChoices,
        null=True,
        on_delete=models.CASCADE
    )


class PatientConsellingQuestionResult(models.Model):
    question_set = models.ForeignKey(
        ConsellingQuestionSets,
        on_delete=models.PROTECT
    )
    patient = models.ForeignKey(
        PatientProfile,
        on_delete=models.PROTECT
    )
    result = models.ManyToManyField(ConsellingQuestionSetsAnswers)
    finding = models.TextField(null=True, blank=True)
    recommendation = models.TextField(null=True, blank=True)
    remarks = models.TextField(null=True, blank=True)
    appointment = models.ForeignKey(
        DoctorVistingSchedules,
        on_delete=models.PROTECT,
        null=True
    )
    assigned_date = models.DateTimeField(
        auto_now=True
    )
    approved_by = models.ForeignKey(
        get_user_model(),
        on_delete=models.PROTECT,
        null=True,
        blank=True
    )
    approved_date = models.DateTimeField(
        null=True,
        blank=True
    )
    approval_status = models.CharField(
        max_length=2,
        choices=APPROVAL_STATUS,
        default=UNAPPROVED,
    )

    class Meta:
        unique_together = ('question_set', 'patient', 'assigned_date')


class LabTestItems(models.Model):
    name = models.CharField(max_length=255, unique=True)
    remark = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name


class LabTests(models.Model):
    name = models.CharField(max_length=255)
    items = models.ManyToManyField(
        LabTestItems
    )
    slug = models.SlugField(
        unique=True,
        allow_unicode=True
    )
    home_service = models.BooleanField(default=False)
    remark = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = get_unique_slug(self, 'name', 'slug')
        super().save(*args, **kwargs)


class Labs(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(
        unique=True,
        allow_unicode=True
    )
    location = models.ForeignKey(
        Location,
        on_delete=models.PROTECT
    )
    tests = models.ManyToManyField(
        LabTests
    )
    remark = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = get_unique_slug(self, 'name', 'slug')
        super().save(*args, **kwargs)


class LabAgentProfile(models.Model):
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )
    lab = models.ForeignKey(
        Labs,
        on_delete=models.PROTECT
    )
    designation = models.ForeignKey(
        Designation,
        on_delete=models.PROTECT
    )
    first_name = models.CharField(
        max_length=255
    )
    middle_name = models.CharField(
        max_length=255,
        blank=True,
        null=True
    )
    last_name = models.CharField(
        max_length=255
    )
    gender = models.CharField(
        max_length=1,
        choices=GENDER
    )
    date_of_birth = models.DateField(
        null=True
    )
    permanent_address = models.ForeignKey(
        Location,
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    profile_pic = models.ImageField(
        upload_to=user_directory_path,
        blank=True,
        null=True
    )
    status = models.CharField(
        max_length=2,
        choices=STATUS,
        default=ACTIVE,
    )
    remark = models.TextField(blank=True, null=True)
    registered_by = models.ForeignKey(
        get_user_model(),
        on_delete=models.PROTECT,
        null=True,
        related_name='labagent_registered_by'
    )

    def __str__(self):
        return self.user.phone_number


class PatientLabTest(models.Model):

app/doctor/views.py
from django.views.generic import TemplateView
from website.mixins import DoctorLoginRequiredMixin


class Dashboard(DoctorLoginRequiredMixin, TemplateView):
    template_name = 'doctor/dashboard.html'

app/healthcare/templates/healthcare/doctor/doctor_degree_form.html
{% extends "core/admin/partials/admin_layout.html" %}
{% load core_extras %}
{% block title %} Doctor Degree | ZenWellness {% endblock title %}
{% block styles %}
  <style>
    .upload_image{
        width: 120px;
        height: 120px;
    }
    .errorlist{
        list-style-type: none;
        color: red;
    }
  </style>
{% endblock styles %}
{% block content %}
<!-- Content Header -->
<section class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        </div>
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{% url 'core:admin_dashboard' %}">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="{% url 'healthcare:doctor_list' %}">Doctors</a></li>
            <li class="breadcrumb-item active">{{ form_title }}</li>
        </ol>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card card-success">
              <div class="card-header">
                <h3 class="card-title">{{ form_title }}</h3>
              </div>

              <form role="form" action="{{ form_action }}" method="POST">
                {% csrf_token %}
                <div class="card-body">
                  <div class="form-group">
                    <label>Degree</label>
                    {{ form.degree | add_class:"form-control select2" }}
                    {{ form.degree.errors }}
                  </div>
                  <div class="form-group">
                    <label>University</label>
                    {{ form.university | add_class:"form-control select2 uniselect" }}
                    {{ form.university.errors }}
                  </div>
                </div>

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
        </div>
    </div>

    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">


</section>
<!-- /.content -->
{% endblock content %}

{% block scripts %}
  <script>
    $('#id_degree').on('change', function(){
        degree = $(this).val();
        $.ajax({
            url: url = "{% url 'core:retrieve_deg_via_uni' %}",
            data: {csrfmiddlewaretoken: '{{ csrf_token }}', 'degree':degree},
            method: 'POST',
            success: function (result) {
                $(".uniselect").select2({
                    placeholder: "Select University",
                    data: result
                });
            },
            error: function(result){
                $(".uniselect").empty().trigger('change')
            }
        });
    });
    
  </script>
{% endblock scripts %}

app/healthcare/templates/healthcare/doctor/doctor_degree_list.html
{% extends "core/admin/partials/admin_layout.html" %}
{% block title %} Doctor Degree List | ZenWellness {% endblock title %}

{% block content %}
<!-- Content Header -->
<section class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        </div>
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{% url 'core:admin_dashboard' %}">Dashboard</a></li>
            <li class="breadcrumb-item active"><a href="{% url 'healthcare:doctor_list' %}">Doctor</a></li>
            <li class="breadcrumb-item active">Doctor Degrees</li>
        </ol>
        </div>
    </div>
    <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">List of Degrees - 
                ( {{ doctor.first_name }} {{ doctor.middle_name }} {{ doctor.last_name }} )</h3>

                <div class="card-tools">
                  <div class="input-group input-group-sm" style="width: 150px;">
                    <a href="{% url 'healthcare:doctor_degree_add' doctor.pk %}">
                        <button class="btn btn-primary btn-sm">
                        <i class="fas fa-plus"></i> Add New Degree</button>
                    </a>
                  </div>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body table-responsive p-0">
                <table class="table table-hover">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Degree</th>
                      <th>University</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for degree in degrees %}
                      <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ degree.degree }}</td>
                        <td>{{ degree.university }}</td>
                        <td>
                          <a class="delete_btn" href="{% url 'healthcare:doctor_degree_delete' degree.pk %}">
                              <button class="btn btn-danger btn-sm">
                              <i class="fas fa-trash"></i> Delete</button>
                          </a>
                        </td>
                      </tr>                      
                    {% endfor %}
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">


</section>
<!-- /.content -->
{% endblock content %}

{% block scripts %}
  <script>
    $('.delete_btn').on('click', function(e){
      e.preventDefault();
      let url = $(this).attr('href');
      Swal.fire({
        title: 'Are you sure?',
        text: "You won't be able to revert this!",
        type: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Yes, delete it!'
      }).then((result) => {
        if (result.value) {
          window.location.href = url;
        }else{
          Swal.fire(
            'Cancelled!',
            'Deletion Process Stopped.',
            'error'
          )          
        }
      });
    })
  </script>
{% endblock scripts %}

app/healthcare/templates/healthcare/doctor/doctor_list.html
{% extends "core/admin/partials/admin_layout.html" %}
{% block title %} Doctor | ZenWellness {% endblock title %}

{% block content %}
<!-- Content Header -->
<section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Doctors</h1>
          </div>
          <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{% url 'core:admin_dashboard' %}">Dashboard</a></li>
              <li class="breadcrumb-item active">Doctors</li>
          </ol>
          <br/>
          <br/>
          <a href="{% url 'healthcare:doctor_add' %}"><button class="btn btn-primary btn-sm float-right">
          <i class="fas fa-plus"></i> Register Doctor</button></a>
          </div>
      </div>
      </div>
</section>
<section class="content">
  <div class="card card-solid">
    <div class="card-body">
    <div class="row">
    {% for doctor in doctors %} 
    
        <div class="col-sm-4">
        <div class="card bg-light">
        <div class="card-header text-muted border-bottom-0">
          {{ doctor.discipline }}
        </div>
        <div class="card-body pt-0">
          <div class="row">
            <div class="col-7">
                <h2 class="lead">
                <b>{{ doctor.designation }}. {{ doctor.first_name }} 
                {% if doctor.middle_name %} {{ doctor.middle_name }} {% endif %}
                {{ doctor.last_name }}</b>
                </h2>
              <ul class="ml-4 mb-0 fa-ul text-muted">
                <li class="small"><span class="fa-li">
                <i class="fas fa-lg fa-building"></i></span>Address: {{ doctor.permanent_address }}</li>
                <li class="small"><span class="fa-li">
                <i class="fas fa-lg fa-phone"></i></span> Phone: {{ doctor.user.phone_number }}</li>
                <li class="small"><span class="fa-li">
                <i class="fas fa-lg fa-user"></i></span> Status: 
                  {% if doctor.user.is_active %}
                    <span class="right badge badge-success">Active</span>
                  {% else %}
                    <span class="right badge badge-danger">In-Active</span>
                  {% endif %}
                </li>       
              </ul>
            </div>
            <div class="col-5 text-center">
              {% if doctor.profile_pic %}
              <img src="{{ doctor.profile_pic.url }}" alt="" class="img-circle img-fluid">
              {% endif %}
            </div>
          </div>
        </div>
        <div class="card-footer">
        <div class="text-right">
        <a href="{% url 'healthcare:doctor_profile_update' doctor.pk %}" class="btn btn-sm bg-teal">
        <i class="fas fa-id-card"></i>
        </a>
        <a href="{% url 'healthcare:doctor_degree_list' doctor.pk %}" class="btn btn-sm bg-blue">
        <i class="fas fa-user-graduate"></i>
        </a>
        <a href="{% url 'healthcare:doctor_change_password' doctor.user.pk %}" 
        class="btn btn-sm bg-blue">
        <i class="fas fa-key"></i>
        </a>
        <a href="{% url 'healthcare:doctor_schedule_list' doctor.pk %}" 
        class="btn btn-sm bg-yellow">
        <i class="fa fa-calendar"></i>
        </a>
        </div>
        </div>
        </div>
        </div>
      
    {% endfor %}
    </div>
    </div>
  </div>
</section>
<!-- Main content -->
<section class="content">


</section>
<!-- /.content -->
{% endblock content %}

app/healthcare/templates/healthcare/doctor/doctor_password_form.html
{% extends "core/admin/partials/admin_layout.html" %}
{% load core_extras %}
{% block title %} Doctor Change Password | ZenWellness {% endblock title %}
{% block styles %}
  <style>
    .upload_image{
        width: 120px;
        height: 120px;
    }
    .errorlist{
        list-style-type: none;
        color: red;
    }
  </style>
{% endblock styles %}
{% block content %}
<!-- Content Header -->
<section class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        </div>
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{% url 'core:admin_dashboard' %}">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="{% url 'healthcare:doctor_list' %}">Doctors</a></li>
            <li class="breadcrumb-item active">Change Password</li>
        </ol>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card card-success">
              <div class="card-header">
                <h3 class="card-title">Change Password</h3>
              </div>

              <form role="form" action="{% url 'healthcare:doctor_change_password' doctor.pk %}" method="POST">
                {% csrf_token %}
                <div class="card-body">
                  <div class="form-group">
                    <label>Password</label>
                    {{ form.password | add_class:"form-control" }}
                    {{ form.password.errors }}
                  </div>
                  <div class="form-group">
                    <label>Password Confirmation</label>
                    {{ form.password_confirmation | add_class:"form-control" }}
                    {{ form.password_confirmation.errors }}
                  </div>
                </div>

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
        </div>
    </div>

    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">


</section>
<!-- /.content -->
{% endblock content %}